"use client";

import React, { useState, useEffect } from "react";
import { DollarSign, FileText, TrendingUp, Building, Clock, CheckCircle } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { apiFetch } from "@/lib/api";

interface Invoice {
  id: string;
  invoice_number: string;
  task_id: string;
  amount: number;
  status: string;
  generated_at: string;
  due_date: string;
  clients: {
    company_name: string;
    contact_email: string;
  };
}

interface FinancePanelProps {
  role: "director" | "employee";
}

export const FinancePanel: React.FC<FinancePanelProps> = ({ role }) => {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchInvoices = async () => {
      try {
        const res = await apiFetch('/api/invoices');
        if (res.ok) {
          const data = await res.json();
          if (data.invoices) setInvoices(data.invoices);
        }
      } catch (err) {
        console.error("Failed to fetch invoices", err);
      } finally {
        setLoading(false);
      }
    };

    fetchInvoices();

    // Listen for new invoices auto-generated by the system
    const invoiceChannel = supabase
      .channel('public:invoices')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'invoices' }, () => {
        fetchInvoices(); // refetch to get client join data
      })
      .subscribe();

    return () => {
      supabase.removeChannel(invoiceChannel);
    };
  }, [role]);

  if (role !== "director") {
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-500">
        <DollarSign className="w-16 h-16 text-slate-300 mb-4 opacity-50" />
        <h2 className="text-xl font-bold uppercase tracking-widest text-slate-400">Restricted Area</h2>
        <p className="text-sm mt-2">You do not have clearance to view financial data.</p>
      </div>
    );
  }

  const totalRevenue = invoices.reduce((sum, inv) => sum + Number(inv.amount), 0);
  const unpaidCount = invoices.filter(i => i.status === 'unpaid').length;

  return (
    <div className="flex flex-col h-full bg-slate-50 dark:bg-slate-950/50 p-6">
      <div className="flex items-center justify-between mb-8 border-b border-slate-200 dark:border-slate-800 pb-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-800 dark:text-slate-100 flex items-center gap-3">
            <TrendingUp className="w-6 h-6 text-emerald-500" />
            FINANCIAL MANAGEMENT SYSTEM
          </h1>
          <p className="text-xs text-slate-500 font-mono mt-1">AUTOMATED BILLING INTERCEPTOR ACTIVE</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Revenue Generated</span>
            <DollarSign className="w-5 h-5 text-emerald-500" />
          </div>
          <div className="text-4xl font-black text-slate-800 dark:text-slate-100">${totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Outstanding Invoices</span>
            <Clock className="w-5 h-5 text-amber-500" />
          </div>
          <div className="text-4xl font-black text-slate-800 dark:text-slate-100">{unpaidCount}</div>
        </div>

        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Projects Billed</span>
            <FileText className="w-5 h-5 text-blue-500" />
          </div>
          <div className="text-4xl font-black text-slate-800 dark:text-slate-100">{invoices.length}</div>
        </div>
      </div>

      <div className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm overflow-hidden flex flex-col">
        <div className="p-4 border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex justify-between items-center">
          <h3 className="font-bold text-sm text-slate-700 dark:text-slate-300">Automated Invoice Ledger</h3>
        </div>
        
        <div className="flex-1 overflow-auto p-4">
          {loading ? (
            <div className="flex items-center justify-center h-full text-slate-500">Decrypting Financial Ledgers...</div>
          ) : invoices.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-slate-500">
              <FileText className="w-12 h-12 text-slate-300 mb-3 opacity-50" />
              <p>No invoices generated yet.</p>
              <p className="text-xs mt-1">Move a budgeted project to COMPLETED to auto-generate an invoice.</p>
            </div>
          ) : (
            <div className="space-y-3">
              {invoices.map(inv => (
                <div key={inv.id} className="flex items-center justify-between p-4 border border-slate-200 dark:border-slate-800 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className="w-10 h-10 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
                      <DollarSign className="w-5 h-5" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <h4 className="font-bold text-sm text-slate-800 dark:text-slate-100">{inv.invoice_number}</h4>
                        <span className="text-[10px] font-mono px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-500 rounded border border-slate-200 dark:border-slate-700">{inv.task_id}</span>
                      </div>
                      <div className="flex items-center gap-3 text-xs text-slate-500 mt-1">
                        <span className="flex items-center gap-1"><Building className="w-3 h-3" /> {inv.clients?.company_name || 'Unknown Client'}</span>
                        <span>•</span>
                        <span>Generated: {new Date(inv.generated_at).toLocaleDateString()}</span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-6">
                    <div className="text-right">
                      <div className="font-black text-lg text-slate-800 dark:text-slate-100">${Number(inv.amount).toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
                      <div className="text-[10px] font-bold text-slate-400 uppercase">Amount Due</div>
                    </div>
                    
                    {inv.status === 'unpaid' ? (
                      <div className="flex items-center gap-1.5 px-3 py-1 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 border border-amber-200 dark:border-amber-800 rounded-full text-xs font-bold uppercase tracking-wider">
                        <Clock className="w-3.5 h-3.5" /> Unpaid
                      </div>
                    ) : (
                      <div className="flex items-center gap-1.5 px-3 py-1 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800 rounded-full text-xs font-bold uppercase tracking-wider">
                        <CheckCircle className="w-3.5 h-3.5" /> Paid
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
